name: Security Scan

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]

jobs:
  vulnerability-scan:
    name: Snyk Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Snyk
        uses: snyk/actions/setup@master

      - name: Run Snyk Code Test
        run: |
          snyk code test nexuslib || true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}